# Generated by Django 2.2 on 2020-01-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200123_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(upload_to='media/shop/product_image/'),
        ),
    ]
