# Generated by Django 2.2 on 2020-01-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200123_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(upload_to='shop/product_image/'),
        ),
    ]
