# Generated by Django 2.2 on 2020-01-23 22:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200123_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
