# Generated by Django 2.2 on 2020-01-24 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200124_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='id',
        ),
        migrations.AlterField(
            model_name='return',
            name='purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='purchase', serialize=False, to='shop.Purchase'),
        ),
    ]
