# Generated by Django 2.2 on 2020-01-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200124_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='return',
            old_name='time',
            new_name='post_time',
        ),
    ]
