# Generated by Django 2.2 on 2020-01-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200125_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='return_status',
            field=models.BooleanField(default=True),
        ),
    ]
